version: '3'
services:

  traefik:
    image: traefik

    environment:
      TRAEFIK_API: "true"
      TRAEFIK_LOG_LEVEL: "DEBUG"
      TRAEFIK_ACCESSLOG: "true"

      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: "host2_default"

      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: ":443"
      TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS: "true"

      # ACME DNS challenge:
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_TLSCHALLENGE: "false"
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_DNSCHALLENGE: "true"
      # TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER: "https://acme-staging-v02.api.letsencrypt.org/directory"

    env_file:
      - .env

    ports:
      - "443:443"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"

    labels:
      # Traefik dashboard:
      traefik.http.routers.traefik.rule: "Host(`traefik-host2.${DOMAIN:?error}`)"
      traefik.http.routers.traefik.service: "api@internal"

      # Lets Encrypt:
      traefik.http.routers.wildcarddomain.service: "noop@internal"
      traefik.http.routers.wildcarddomain.tls.certResolver: "letsencrypt"
      "traefik.http.routers.wildcarddomain.tls.domains[0].main": "*.${DOMAIN:?error}"
      "traefik.http.routers.wildcarddomain.tls.domains[0].sans": "${DOMAIN:?error}"

      # middleware for Authelia on host1:
      traefik.http.middlewares.authelia.forwardauth.address: "https://autheliatest.${DOMAIN:?error}/api/verify?rd=https%3A%2F%2Fautheliatest.${DOMAIN:?error}%2F"
      traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: "true"
      traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: "Remote-User,Remote-Groups,Remote-Name,Remote-Email"

  service:
    image: traefik/whoami
    labels:
      traefik.http.routers.service.rule: Host(`service-host2.${DOMAIN:?error}`)
      traefik.http.routers.service.middlewares: "authelia@docker"
